### ISSUE TITLE
Support setting fsbase and gsbase for a host execution context

### ISSUE THREAD

**Issue by bjorn3** [udosteinberg/NOVA#6]
Either by setting the FSGSBASE bit of CR4 to enable the rdfsbase, rdgsbase, wrfsbase and wrgsbase instructions in userspace, or through some other means like adding them to the UTCB for host execution contexts. I'm not sure how I can implement thread local storage without this.

**Comment by udosteinberg** [comment]
We implement thread-local storage in an architecture-independent manner (i.e. without segment registers) by rounding (up or down) each thread's stack pointer to get to the TLS area, which is allocated adjacent to the thread's stack.

**Comment by bjorn3** [comment]
That's a clever way to implement TLS. It doesn't work when doing stack switching, but I presume none of the intended use cases for NOVA actually need that. It also doesn't seem like it is compatible with the relaxation from `__tls_get_addr` to `mov rax, %fs:-some_offset` that the linker does for tls accesses in the main executable. Are you skipping ELF tls handling entirely in favor of manual calls to the TLS access functions?

**Comment by udosteinberg** [comment]
Yes, we do TLS without help from the linker.
I'm not totally opposed to doing something different, but whatever we do needs to work for all supported architectures and needs to be light-weight. I'd rather round a stack-pointer (which is effectively an `AND` instruction) instead of paying the overhead of switching segment registers all the time.

**Comment by bjorn3** [comment]
Thanks for the explanation!
